import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keyword"
          content="next app, blog, next blog, hunting coder, blog website"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coders</h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn React Js in 2022?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit
              temporibus magnam at architecto dolorum nisi eaque nihil quod
              perferendis sapiente.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn React Js in 2022?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit
              temporibus magnam at architecto dolorum nisi eaque nihil quod
              perferendis sapiente.
            </p>
          </div>

          <div className="blogItem">
            <h3>How to learn React Js in 2022?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit
              temporibus magnam at architecto dolorum nisi eaque nihil quod
              perferendis sapiente.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
